on:
  workflow_dispatch:

name: revdepcheck

jobs:
  revdepcheck:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: revdep
          extra-packages: |
            local::.
            any::usethis
            any::BiocManager
            any::BiocVersion
            any::devtools
            any::remotes
            r-lib/revdepcheck
          needs: check

      - name: revdepcheck
        run: |

          revdepcheck::revdep_reset()
          revdepcheck::revdep_check(num_workers = 4)


          revdepig <- c(
            "checks", "library", "checks.noindex", "library.noindex",
            "data.sqlite", "*.html" )

          usethis::use_git_ignore(revdepig, directory = file.path(".", "revdep"))

          # Ignore this also on build
          usethis::use_build_ignore("revdep")

        shell: Rscript {0}

      - name: Commit results
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m 'revdepcheck' || echo "No changes to commit"
          git push origin || echo "No changes to commit"

